apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-api
spec:
  # How many copies of each pod do we want?
  replicas: 2
  selector:
    matchLabels:
      # This must match the labels we set on the pod!
      app: front-api
  # This template field is a regular pod configuration
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: front-api
    spec:
      containers:
        - name: front-api
          image: gcr.io/sambo-project/python
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: DEV
            - name: HOST
              value: localhost
            - name: PORT 
              value: "8000"
            - name: REDIS_HOST 
              value: localhost
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"